### ISSUE TITLE
Error with utils.py when using float signals with scaling

### ISSUE THREAD

**Issue by ghost** [kdschlosser/vector_dbc#2]
Hi,

this function in utils.py:

```
def _encode_field(field, data, scaling):
    value = data[field.name]

    if isinstance(value, str):
        return field.choice_string_to_number(value)
    elif scaling:
        if field.is_float:
            return (value - field.offset) / field.scale
        else:
            value = (Decimal(value) - Decimal(field.offset)) / Decimal(field.scale)

            return int(value.to_integral())
    else:
        return value
```

causes _"TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'_ when you defined the signal as float with a decimal scaling in the dbc file, and you're also assigning the signal a decimal value.

The exact line that causes the failure is this one:

`return (value - field.offset) / field.scale`

**Comment by kdschlosser** [comment]
I will take a look at it this evening.

**Comment by ghost** [comment]
Thanks for looking into it.

The crash happens when you call the encode-method on a message having a float signal as described above.

**Comment by kdschlosser** [comment]
Because you are set up to produce this error can you do me a favor?

Can you add this line before `return (value - field.offset) / field.scale`

```python
print(type(value), type(field.offset), type(field.scale))
```

And post the output for me. I need to know what the data types are as I believe it is having an issue because some of them are decimal.Decimal and I need to know which one(s) are not.

**Comment by ghost** [comment]
> Can you add this line before `return (value - field.offset) / field.scale`
> 
> ```python
> print(type(value), type(field.offset), type(field.scale))
> ```
> 
> And post the output for me. I need to know what the data types are as I believe it is having an issue because some of them are decimal.Decimal and I need to know which one(s) are not.

Sure, here's the output:

<class 'float'> <class 'int'> <class 'decimal.Decimal'>

By the way, I was able to fix it by casting field.scale to float:

`return (value - field.offset) / float(field.scale)`

But I would feel a lot better about it, if you would approve that fix (or make your own), given that you know the code far better than I do.

**Comment by kdschlosser** [comment]
you don't want to cast it to a float tho. This is because of floating point math errors that happen when using Python.

if you run this code

```python
print(1.2 - 1.0)
```

you are expecting the output to be `0.2` but it's not. The output is `0.199999999999999996`. so `decimal.Decimal` is used to correct those kinds of errors in floating point math. 


You need to check and see if the `decimal` library is imported in that file and if it's not then it needs to be added and the line changed to 
```python
return (decimal.Decimal(str(value)) - decimal.Decimal(str(field.offset)) / field.scale
```

**Comment by kdschlosser** [comment]
actually it needs to be


```python
def _encode_field(field, data, scaling):
    value = data[field.name]

    if isinstance(value, str):
        return field.choice_string_to_number(value)
    elif scaling:
        value = (Decimal(value) - Decimal(field.offset)) / Decimal(field.scale)

        if field.is_float:
            return float(value)
        else:
            return int(value.to_integral())
    else:
        return value
```
